peso = float(input("Ingrese su peso en kilogramos: "))
estatura = float(input("Ingrese su estatura en metros: "))
imc = peso / (estatura ** 2)
imc_redondeado = round(imc, 2)
print("Tu índice de masa corporal (IMC) es:", imc_redondeado)